export const actionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT"
};
